version: "3.7"

services:
  frontend:
    image: antontrofimovich/at-recipes-front
    ports:
      - 4200:4200

  backend:
    image: antontrofimovich/at-recipes-back
    ports:
      - 3000:3000

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: recipes